### ISSUE TITLE
User created but unable to login 

### ISSUE THREAD

**Issue by edersong** [FSchiltz/Helse#98]
Followed the steps to create an Admin user and it just reported `Error: Exception:`
Refreshed page and when tried to login with the same user and password it reports the same error.
Here is what app is reporting on container logs:
```
info: Auth[0]
05/07/2024
10:10:51 PM
      Connexion by username
05/07/2024
10:10:51 PM
fail: Microsoft.AspNetCore.Server.Kestrel[13]
05/07/2024
10:10:51 PM
      Connection id "0HN3EQ4HUTNJT", Request id "0HN3EQ4HUTNJT:00000001": An unhandled exception was thrown by the application.
05/07/2024
10:10:51 PM
      System.ArgumentOutOfRangeException: IDX10720: Unable to create KeyedHashAlgorithm for algorithm 'http://www.w3.org/2001/04/xmldsig-more#hmac-sha512', the key size must be greater than: '512' bits, key has '256' bits. (Parameter 'keyBytes')
05/07/2024
10:10:51 PM
         at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.ValidateKeySize(Byte[] keyBytes, String algorithm, Int32 expectedNumberOfBytes)
05/07/2024
10:10:51 PM
         at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateKeyedHashAlgorithm(Byte[] keyBytes, String algorithm)
05/07/2024
10:10:51 PM
         at Microsoft.IdentityModel.Tokens.SymmetricSignatureProvider.CreateKeyedHashAlgorithm()
05/07/2024
10:10:51 PM
         at Microsoft.IdentityModel.Tokens.DisposableObjectPool`1.CreateInstance()
05/07/2024
10:10:51 PM
         at Microsoft.IdentityModel.Tokens.DisposableObjectPool`1.Allocate()
05/07/2024
10:10:51 PM
         at Microsoft.IdentityModel.Tokens.SymmetricSignatureProvider.GetKeyedHashAlgorithm(Byte[] keyBytes, String algorithm)
05/07/2024
10:10:51 PM
         at Microsoft.IdentityModel.Tokens.SymmetricSignatureProvider.Sign(Byte[] input)
05/07/2024
10:10:51 PM
         at Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.CreateEncodedSignature(String input, SigningCredentials signingCredentials)
05/07/2024
10:10:51 PM
         at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials, IDictionary`2 claimCollection, String tokenType, IDictionary`2 additionalHeaderClaims, IDictionary`2 additionalInnerHeaderClaims)
05/07/2024
10:10:51 PM
         at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateToken(SecurityTokenDescriptor tokenDescriptor)
05/07/2024
10:10:51 PM
         at Api.Helpers.Auth.TokenService.GetToken(List`1 claims, DateTime expires) in /source/Helpers/Auth/TokenService.cs:line 68
05/07/2024
10:10:51 PM
         at Api.Helpers.Auth.TokenService.GetAccessToken(TokenInfo info, DateTime expires) in /source/Helpers/Auth/TokenService.cs:line 54
05/07/2024
10:10:51 PM
         at Api.Logic.Auth.AuthLogic.AuthAsync(Connection user, ISettingsContext settings, IUserContext users, HttpContext context, TokenService token, ILoggerFactory logger) in /source/Logic/Auth/AuthLogic.cs:line 121
05/07/2024
10:10:51 PM
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.ExecuteTaskResult[T](Task`1 task, HttpContext httpContext)
05/07/2024
10:10:51 PM
         at Microsoft.AspNetCore.Http.RequestDelegateFactory.<>c__DisplayClass102_2.<<HandleRequestBodyAndCompileRequestDelegateForJson>b__2>d.MoveNext()
05/07/2024
10:10:51 PM
      --- End of stack trace from previous location ---
05/07/2024
10:10:51 PM
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
05/07/2024
10:10:51 PM
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
05/07/2024
10:10:51 PM
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
05/07/2024
10:10:51 PM
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
05/07/2024
10:10:51 PM
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

**Comment by FSchiltz** [comment]
It looks like the key you choose in your config is only 256bits and asp.net expect one of 512bit length.
this is something I can fix by adding padding or by using a random key persisted to a volume instead of having the user specify it.
If you want to continue you can add more text to your key to test if it's that.

**Comment by edersong** [comment]
Worked!
Now put an JWT 256bits length

**Comment by FSchiltz** [comment]
I've made an update where I pad to key so any key lenght will works.
